"""
payment_bridge.py - Stripe webhook receiver for the "Pay By Link" flow.

When a customer pays a Stripe checkout link (generated by stripe_pay for a
"Pay By Link" order), Stripe POSTs an event here. We verify the signature,
pull the CRM order_id back out of the session metadata / client_reference_id,
find the order in Notion, and stamp it paid:
  - INTERNAL NOTE  -> "Bot log: Paid and Confirmed"  (mirrors the COD confirm)
  - "Paid via Stripe" checkbox -> True
The sales team processes it from there. We do NOT change ORDER STATUS (same as
the COD confirm handler).

HTTPS is required by Stripe, so this binds 127.0.0.1 and Caddy fronts it at
https://<domain>/stripe/webhook. Origin is proven by Stripe's signature (not a
path secret).

Endpoints:
  GET  /                health check ("payment-bridge up")
  POST /stripe/webhook  Stripe event

Run: python3 execution/payment_bridge.py
"""
from __future__ import annotations

import asyncio
import hashlib
import hmac
import json
import logging
import os
import signal
import sys
import time
from collections import deque
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "execution"))
load_dotenv(PROJECT_ROOT / ".env")

import notion_client as notion

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("payment-bridge")

HOST = os.getenv("PAYMENT_BRIDGE_HOST", "127.0.0.1")
PORT = int(os.getenv("PAYMENT_BRIDGE_PORT", "8087"))
WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
SIG_TOLERANCE_S = int(os.getenv("STRIPE_SIG_TOLERANCE_S", "300"))

# Events that mean "money captured" for a payment-mode Checkout Session.
PAID_EVENTS = {"checkout.session.completed", "checkout.session.async_payment_succeeded"}

# Small in-memory idempotency guard (mark_stripe_paid is itself idempotent, so
# this is just noise-reduction against Stripe's at-least-once retries).
_seen_events: deque = deque(maxlen=2000)
_seen_set: set = set()


def _already_seen(event_id: str) -> bool:
    if not event_id:
        return False
    if event_id in _seen_set:
        return True
    _seen_events.append(event_id)
    _seen_set.add(event_id)
    while len(_seen_set) > _seen_events.maxlen:
        _seen_set.discard(_seen_events.popleft())
    return False


def verify_signature(payload: bytes, sig_header: str, secret: str, now: float = None) -> bool:
    """Verify Stripe's `Stripe-Signature` header (HMAC-SHA256 of `t.payload`)."""
    if not secret or not sig_header:
        return False
    now = time.time() if now is None else now
    t = None
    v1s = []
    for part in sig_header.split(","):
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        k = k.strip()
        if k == "t":
            t = v.strip()
        elif k == "v1":
            v1s.append(v.strip())
    if not t or not v1s:
        return False
    try:
        if SIG_TOLERANCE_S and abs(now - int(t)) > SIG_TOLERANCE_S:
            log.warning("stripe signature timestamp outside tolerance")
            return False
    except ValueError:
        return False
    signed = t.encode() + b"." + payload
    expected = hmac.new(secret.encode(), signed, hashlib.sha256).hexdigest()
    return any(hmac.compare_digest(expected, v1) for v1 in v1s)


def _order_id_from_session(obj: dict) -> str:
    md = obj.get("metadata") or {}
    return (md.get("order_id") or obj.get("client_reference_id") or "").strip()


def handle_event(event: dict) -> None:
    """Process one verified Stripe event."""
    etype = event.get("type", "")
    event_id = event.get("id", "")
    if etype not in PAID_EVENTS:
        log.debug(f"ignoring event {etype}")
        return
    if _already_seen(event_id):
        log.info(f"duplicate event {event_id} - skipping")
        return

    obj = (event.get("data") or {}).get("object") or {}
    # Guard: only act on actually-paid sessions.
    if obj.get("payment_status") not in (None, "paid"):
        log.info(f"{etype} session not paid (payment_status={obj.get('payment_status')}) - skipping")
        return

    order_id = _order_id_from_session(obj)
    if not order_id:
        log.warning(f"{etype} {event_id}: no order_id in metadata/client_reference_id - skipping")
        return

    amount = obj.get("amount_total")
    log.info(f"paid: order {order_id} (event {event_id}, amount {amount})")

    try:
        order = notion.find_order_by_id(order_id)
    except Exception as e:
        log.error(f"Notion lookup failed for {order_id}: {e}")
        return
    if not order:
        log.warning(f"order {order_id} not found in Notion - cannot stamp paid")
        return

    ok = notion.mark_stripe_paid(order["page_id"])
    if ok:
        log.info(f"{order_id} stamped: 'Bot log: Paid and Confirmed' + Paid via Stripe")
    else:
        log.error(f"failed to stamp {order_id} paid in Notion")


# ------------------------------------------------------------------
# Minimal HTTP server (same raw-asyncio pattern as rescue_server)
# ------------------------------------------------------------------

async def handle_connection(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
    try:
        header_bytes = bytearray()
        while True:
            chunk = await reader.read(4096)
            if not chunk:
                break
            header_bytes.extend(chunk)
            if b"\r\n\r\n" in header_bytes:
                break
            if len(header_bytes) > 262144:
                break
        if b"\r\n\r\n" not in header_bytes:
            writer.close()
            return

        head, _, rest = header_bytes.partition(b"\r\n\r\n")
        lines = head.decode("iso-8859-1", errors="replace").split("\r\n")
        first = lines[0].split()
        if len(first) < 2:
            writer.close()
            return
        method, path = first[0].upper(), first[1].split("?", 1)[0]

        headers = {}
        for line in lines[1:]:
            if ":" in line:
                k, v = line.split(":", 1)
                headers[k.strip().lower()] = v.strip()

        if method in ("GET", "HEAD") and path in ("/", "/health"):
            body = b"payment-bridge up"
            writer.write(
                b"HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n"
                b"Content-Length: " + str(len(body)).encode() + b"\r\n"
                b"Connection: close\r\n\r\n" + (b"" if method == "HEAD" else body)
            )
            await writer.drain()
            writer.close()
            return

        if method != "POST" or path != "/stripe/webhook":
            writer.write(b"HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n")
            await writer.drain()
            writer.close()
            return

        length = int(headers.get("content-length", "0") or 0)
        body = bytes(rest)
        while len(body) < length:
            chunk = await reader.read(min(65536, length - len(body)))
            if not chunk:
                break
            body += chunk
        body = body[:length]

        sig = headers.get("stripe-signature", "")
        if not verify_signature(body, sig, WEBHOOK_SECRET):
            log.warning("rejected webhook: bad/missing signature")
            writer.write(b"HTTP/1.1 400 Bad Request\r\nContent-Length: 0\r\nConnection: close\r\n\r\n")
            await writer.drain()
            writer.close()
            return

        # Ack fast; process after responding.
        writer.write(b"HTTP/1.1 200 OK\r\nContent-Length: 2\r\nConnection: close\r\n\r\nok")
        await writer.drain()
        writer.close()

        try:
            event = json.loads(body.decode("utf-8", errors="replace"))
        except Exception as e:
            log.warning(f"bad webhook JSON: {e}")
            return
        try:
            handle_event(event)
        except Exception as e:
            import traceback
            log.error(f"handle_event crashed: {e}\n{traceback.format_exc()}")

    except (ConnectionResetError, asyncio.IncompleteReadError, BrokenPipeError, TimeoutError) as e:
        log.debug(f"connection dropped: {e}")
        try:
            writer.close()
        except Exception:
            pass
    except Exception as e:
        import traceback
        log.error(f"connection handler crashed: {e}\n{traceback.format_exc()}")
        try:
            writer.close()
        except Exception:
            pass


async def main():
    log.info("=" * 60)
    log.info("  payment-bridge - Stripe Pay-By-Link webhook receiver")
    log.info(f"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    log.info(f"  Listening: {HOST}:{PORT}   secret set: {bool(WEBHOOK_SECRET)}")
    log.info("=" * 60)
    if not WEBHOOK_SECRET:
        log.warning("STRIPE_WEBHOOK_SECRET not set - all webhooks will be rejected until it is.")

    server = await asyncio.start_server(handle_connection, HOST, PORT)
    log.info(f"listening on {HOST}:{PORT}")

    stop = asyncio.Event()
    loop = asyncio.get_running_loop()
    for s in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(s, stop.set)
        except NotImplementedError:
            pass
    async with server:
        await stop.wait()
    log.info("shutting down")


if __name__ == "__main__":
    try:
        import error_reporter
        error_reporter.install("payment-bridge", host="gcp-vm")
    except Exception as e:
        log.warning(f"error_reporter not installed: {e}")
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
