"""
tjr_poll.py
===========
Keep TJR Deliveries true, the way filex_reconcile keeps Filex Deliveries true.

Filex has had a poller since the beginning: every five minutes it asks the
courier about every parcel still out and writes back what changed. TJR has
never had one. Its parcels arrive in GRQ OS at `Created` - because that is
what `/pvt all` sets when the label is printed - and they stay at `Created`
forever, whatever the driver actually does. The section exists, the tabs
exist, and every parcel in it is permanently Pending.

That is not a small cosmetic gap. It means the private driver's half of the
business is invisible: nobody can see what was delivered today, nothing
triggers an out-for-delivery message, and a parcel that came back never
opens a return receipt.

The shape is deliberately the same as the Filex one, because it is the same
job:

    GRQ OS  ->  which parcels are still out with TJR, and their tracking ids
    TJR     ->  what each of those is now
    GRQ OS  ->  the ones that changed, through /api/ingest/courier

TJR is our own system, so this reads its database directly rather than an
API. The credentials are the ones tjr_core already uses, in
tjr-logistics/.env, which is why that file is loaded alongside this one.

Two things it deliberately does not do.

It does not map statuses. `/api/ingest/courier` puts the courier's word
through `status_options` and decides what it means for the order - and
refuses one it does not recognise rather than guessing. A second copy of
that table here would drift from the first, and the drift would be silent.

It does not touch parcels GRQ OS considers finished. `parcels_in_flight`
excludes delivered, returned and cancelled, so a stale TJR row cannot
un-deliver an order somebody has already closed.

    python3 execution/tjr_poll.py            # one pass
    python3 execution/tjr_poll.py --dry-run  # say what would change
    python3 execution/tjr_poll.py --days 30  # widen the window
"""
from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import httpx
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(PROJECT_ROOT / ".env")

# TJR is a separate Supabase project with its own credentials. Loaded second
# and without override, so a name the two files share keeps this box's value.
TJR_ENV = Path(os.getenv("TJR_REPO", "/home/bilal/tjr-logistics")) / ".env"
if TJR_ENV.exists():
    load_dotenv(TJR_ENV, override=False)

import grq_os_ingest
import grq_os_work as grqw

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("tjr_poll")

TJR_URL = (os.getenv("TJR_SUPABASE_URL") or os.getenv("SUPABASE_URL") or "").strip().rstrip("/")
TJR_KEY = (os.getenv("TJR_SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_SERVICE_ROLE_KEY") or "").strip()
TENANT  = (os.getenv("TJR_TENANT_ID") or "").strip()


def tjr_statuses(client: httpx.Client, tracking_ids: list[str]) -> dict[str, dict]:
    """
    What TJR says about these parcels, keyed by tracking id.

    Chunked because the ids go in the URL and a hundred of them is a long
    one. PostgREST takes `in.(a,b,c)`; the ids are generated by tracking.py
    and contain no commas or quotes, so they need no escaping - said out
    loud because it would stop being true the day somebody changes the
    generator.
    """
    out: dict[str, dict] = {}
    for i in range(0, len(tracking_ids), 50):
        chunk = tracking_ids[i:i + 50]
        res = client.get(
            f"{TJR_URL}/rest/v1/orders",
            params={
                "select": "tracking_id,status,updated_at",
                "tracking_id": f"in.({','.join(chunk)})",
                **({"tenant_id": f"eq.{TENANT}"} if TENANT else {}),
            },
            headers={"apikey": TJR_KEY, "Authorization": f"Bearer {TJR_KEY}"},
            timeout=30.0,
        )
        if res.status_code != 200:
            log.error("TJR returned %s: %s", res.status_code, res.text[:200])
            continue
        for row in res.json():
            out[row["tracking_id"]] = row
    return out


def same(a: str | None, b: str | None) -> bool:
    """`out_for_delivery` and `Out for delivery` are one status, not two."""
    norm = lambda s: (s or "").strip().lower().replace(" ", "_")
    return norm(a) == norm(b)


def poll_once(within_days: int = 21, dry_run: bool = False) -> int:
    if not (TJR_URL and TJR_KEY):
        log.error("TJR Supabase credentials are not set (SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY)")
        return 0
    if not grqw.configured():
        log.error("GRQ_OS_URL / GRQ_OS_INGEST_SECRET are not set")
        return 0

    parcels = grqw.parcels_in_flight(within_days=within_days, courier="tjr")
    if not parcels:
        log.info("No TJR parcels in flight.")
        return 0

    by_tracking = {p["tracking_number"]: p for p in parcels if p.get("tracking_number")}
    if not by_tracking:
        # Every in-flight TJR parcel with no tracking id is one /pvt all
        # created without recording what TJR called it. Worth saying.
        log.warning("%d TJR parcel(s) in flight and not one has a tracking id", len(parcels))
        return 0

    log.info("Asking TJR about %d parcel(s).", len(by_tracking))

    with httpx.Client() as client:
        theirs = tjr_statuses(client, list(by_tracking))

    missing = set(by_tracking) - set(theirs)
    if missing:
        # A tracking id GRQ OS holds that TJR has never heard of. Rare, and
        # it means the two disagree about a real parcel, so it is an error
        # rather than a shrug.
        log.error("TJR does not know %d tracking id(s): %s",
                  len(missing), ", ".join(sorted(missing)[:10]))

    changed = 0
    for tracking, row in theirs.items():
        ours = by_tracking[tracking]
        if same(row.get("status"), ours.get("delivery_status")):
            continue

        log.info("  %-12s %s -> %s", ours.get("order_code"),
                 ours.get("delivery_status") or "(none)", row.get("status"))
        changed += 1
        if dry_run:
            continue

        # The mapping lives on the far side, in status_options, so there is
        # one copy of it. An unrecognised word is refused there, loudly.
        if not grq_os_ingest.courier({
            "order_code": ours.get("order_code"),
            "courier": "tjr",
            "status": row.get("status"),
            "awb": tracking,
            "at": row.get("updated_at"),
        }):
            log.error("  GRQ OS would not take the update for %s", ours.get("order_code"))

    log.info("%d parcel(s) changed%s.", changed, " (dry run, nothing written)" if dry_run else "")
    return changed


def main() -> int:
    ap = argparse.ArgumentParser(description="Reconcile TJR delivery statuses into GRQ OS.")
    ap.add_argument("--days", type=int, default=21, help="how far back to look for parcels still out")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    poll_once(within_days=args.days, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    try:
        import error_reporter
        error_reporter.install("tjr-poll", host="gcp-vm")
    except Exception:
        pass
    sys.exit(main())
